---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incentive-2021-bff
  namespace: bi-web
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-bi-web-incentive-2021-bff
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-bi-web-incentive-2021-bff
    spec:
      affinity: {}
      containers:
        - env:
            - name: spring.application.name
              value: spring-boot-hello
          image: t4f.io/bi-web/spring-boot-hello:1.0.0
          imagePullPolicy: Always
          name: api
          resources: {}
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /test/hello
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: t4f.io-registry-dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler